### ISSUE TITLE
Set up Use Case / User Story tickets / contribution structure.

### ISSUE THREAD

**Issue by cmharlow** [LD4P/ld4-community-recon#17]
Possibly grab the start from the Islandora work. Need to then get @arwenhutt's feedback, then group feedback, then kick off plan for filling in.

**Comment by arwenhutt** [comment]
@cmh2166 
I've been looking at the Islandora Use Case template and some examples and it seems like it could work well for us.  It's simple and flexible, and seems good for helping us to identify common threads/functions.

I can add a ticket with the template to the Use Case project, and add some things I'm thinking about.

**Comment by ajs6f** [comment]
I've seen the Islandora templates work really well in that community.

**Comment by cmharlow** [comment]
See #20 for template

**Comment by cmharlow** [comment]
Added the use case work framework here: https://github.com/LD4P/ld4-community-recon/wiki/Entity-Resolution,-Reconciliation,-and-Lexicalization-Use-Cases-Work & sent to group for review. leaving this ticket open for another week for feedback or any other discussion on this.

**Comment by cmharlow** [comment]
closing based off of feedback at our 6-19 call.
