### ISSUE TITLE
Title/Goal - e.g. Use Case Template

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#20]
## Primary Actor
Repository architect, implementer, repository admin, user

## Scope
The scope of the project. Example: inter-institutional, intra-institutional, ??

## Level
The priority the use case should be given; High, Medium, Low

## Story
User story
 
## Examples
* Bullet 
* Listed
* Examples should you want to provide them.
 
## Remarks 
* Bullet
* Listed
* Remarks or other thoughts should you want to provide them.
 
## Consensus
*will be recorded in comments*

**Comment by ajs6f** [comment]
`Scope` might be able to say something about whether the use case is intra- or inter- institution, which is going to matter for the kind of stuff we're talking about.

**Comment by arwenhutt** [comment]
Yeah, I wasn't really sure how to apply scope.  That could be a good use of it.  @ajs6f what do you think about the "remarks" and "consensus" bits?  Better in the top level use case description or in comments?

**Comment by ajs6f** [comment]
`Consensus` I could definitely see sending to the comments. `Remarks`? Hm. In an ideal world people who put in use cases would just feel okay putting free-form narrative at the bottom of the post. But it does seem to me that having a specific space for it is, um, helpfully invitational? (Awkward phrasing, but you know what I mean?)

**Comment by arwenhutt** [comment]
Yup.  I wasn't sure in the original Islandora template if Remarks were meant for the person creating the use case or for discussion of it, but I think you're probably right - good to give people a nudge to include any other thoughts that don't fit in the template.

**Comment by cmharlow** [comment]
thanks for grabbing this, @arwenhutt + for input @ajs6f. where would we like to add/manage use cases? wiki? in the repo as .md files?

**Comment by arwenhutt** [comment]
Hmmm, I was thinking each use case could, at least initially, be a ticket in this project.  It'll allow some case by case discussion, we can link or merge related/duplicate cases, and maybe use epics to bring them together (if it ends up making sense) for later work.

**Comment by arwenhutt** [comment]
One other thought, there are lots of different levels that these use cases can be pitched at from granular functionality (i.e. match against multiple vocabularies) to broader ones (i.e. support batch reconciliation for bulk ingests).  It seems like it would make sense to encourage/accept a variety of "levels", they could be complimentary both important for some of our downstream goals of 1) workflow models and 2) specific tools needed. Plus, getting a shared understanding, let alone agreement, on one level seems difficult - though it may emerge organically eventually.

**Comment by ajs6f** [comment]
Using Github (which is fundamentally a software dev tool) to do management for other kinds of work has become a time-honored tradition by now. :) And in that light, tickets are the natural idiom. Agreed about the various levels/scopes/scales/altitudes that will and should be engaged.

**Comment by cmharlow** [comment]
okay, let's get this written up / formalized somewhere.

**Comment by cmharlow** [comment]
captured in work framework here: https://github.com/LD4P/ld4-community-recon/wiki/Entity-Resolution,-Reconciliation,-and-Lexicalization-Use-Cases-Work and covered by #17 . Leaving this open for folks to see template / discuss template specifically as needed.

**Comment by arwenhutt** [comment]
Current version of template: https://github.com/LD4P/ld4-community-recon/blob/master/issue_template.md
