### ISSUE TITLE
Human review of low confidence matches

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#21]
## Primary Actor
Cataloger, Metadata Specialist/Analyst

## Scope
?

## Story
When doing entity resolution low confidence matches should be presented for human review and selection/rejection.  This would be made easier by a presentation of information that supports the evaluation in a way that disrupts the overall workflow as little as possible.  

Factors might include: 
* minimizing need to navigate away from the main interface unless necessary
* side by side comparison of matches from multiple vocabularies (would be especially awesome if these could be compressed/deduped for records from different vocabularies which represent the same identity)
* simple selection of chosen entity
* information which shows local usage of matched ID's (improve intra-repository consistency)
* information from the matched records (i.e. birth and death dates, scope notes, etc.)
* information from the item(s) the entity is being linked too (more of an issue for retrospective or batch entity resolution)
 
## Remarks 
* "Low confidence" and "high confidence" will be variable depending on matching processes used and possibly individual institutions comfort level with algorithmic matching.
* This is presuming that in a decent number of cases "high confidence" matches (again, variable) will be auto linked/assigned.
* Identification of what information is useful for human evaluation seems another important issue, which probably overlaps heavily with the algorithms for machine matching.
 
## Related issues
#55
#71

**Comment by cmharlow** [comment]
are we capturing these as issues?
