### ISSUE TITLE
"Lexicalization" in scope?

### ISSUE THREAD

**Issue by aisaac** [LD4P/ld4-community-recon#30]
Getting a label sounds strange as a case of "reconciliation" as now listed at https://github.com/LD4P/ld4-community-recon. 
"entity/URI to entity/URI" and "string to entity/URI" (the first two bullets in scope) are key. "entity/URI to string" will be needed, but I see it rather as something that contributes to the first too major goals, with other things like dictionaries/synonym lists ("string to string"). Maybe one can say that the first two cases add data to the existing data, while "entity/URI to string" just provides/serves existing data. 
Or am I missing an important point in what is meant by "lexicalization" on the charter?
NB: I won't make a fuss about this if the group keeps it. It just struck me as one point where the charter could be simplified. The group's plate is already quite full, and adding things like vocabulary services in the tools to survey would add a lot.

**Comment by ajs6f** [comment]
Agreed, and frankly, that's pushing the word "reconcilliation" a bit far for my prudish tastes. @azaroth42 (I think it was he!) has already pointed out that we want be able to distinguish reconciliation and resolution (which is itself sometimes called recognition). I haven't heard anyone outside this community use the word "reconciliation" to refer to id-to-label, and it's actually kind of the opposite...

**Comment by cmharlow** [comment]
For what it's worth, including the full scope of what "reconciliation" could be / has been (perhaps incorrectly) in library space was meant to give people a push to clarify their terms when proposing goals, use cases, etc. i.e., it has the same goal as you in discussing it now.

lexicalisation is not listed explicitly in any of the actual work plan or goals at present, and i don't think has come up in the use cases yet. (by which i mean, if it comes up explicitly as a work goal, we can at that point say 'out of scope'). Open to PRs to the README.md that adds to that side note about what reconciliation could include that adds a 'mostly likely out of scope' comment for the rest of the group to review.

**Comment by cmharlow** [comment]
made a stab at rewording: https://github.com/LD4P/ld4-community-recon/blob/cmh2166.READMElex/README.md#30

**Comment by ajs6f** [comment]
Seems okay to me. I'm really mostly concerned about the use of language-- we don't want products from this group to use language in ways that don't match the rest of the world! :)

**Comment by aisaac** [comment]
Looking at
https://github.com/LD4P/ld4-community-recon/blob/cmh2166.READMElex/README.md#30
I agree with the intention behinds the new wording, but is it possible to get a simple wording?
Something like
[
Nota Bene: Reconciliation has been used to mean a number of things in our domain and community work. At this point, we are primarily thinking about these two topics
     Reconciliation (in specific sense): entity/URI to entity/URI
     Entity resolution: string to entity/URI (what most people are thinking about, it appears)
But the community working group may extend this understanding later on.
]

If lexicalization is not in the intended scope so far, then from an editorial it's better if it's not mentioned at the same level (i.e. bullet list) as the others. It's even simpler if it's nowhere :-) As said, I'd be very surprised if it shows up as a case of reconciliation anyway. I trust it will naturally show up as a means for reconciliation, not a target.

**Comment by cmharlow** [comment]
@ajs6f do you see any use of language here that doesn't match with the rest of the world (or worlds)? please, let's fix that! i don't see anything yet that does that (under-specifies, sure, but I see the issue of reconciliation being used to mean everything as one of the issues we are working to fix, yeah?).

@aisaac i'm disinclined, personally, to simplify by removing a definition from a clarification note because a few of us don't see it as in work scope, especially when the work scope is separately described. I think it is important that we make explicit what terms we are using how from the jump, so that everyone in the group - especially those who are learning - have a shared set of understandings. Otherwise, this decision becomes implicit, and that doesn't help transparency or folks entering this work area from communities that maybe aren't using these terms precisely. Unfortunately, I've seen lexicalization or vocab look-ups being confused with "reconciliation" as of late, so wanted to separate those out here.

I can see your point about the bullet list though, and will try another re-word.

From all this, as the use cases come in and we get a better understanding of what people are wanting to work on re:matching, we might expand the group name to "Reconciliation & Resolution" to be more explicit in our scope.

**Comment by ajs6f** [comment]
I understood:

> Here, we are primarily thinking about the first two topics listed of the three topics possibly including in a broader understanding of "reconciliation":

to end up including lexicalization as a part of what we might be meaning by "reconciliation". I've never heard that usage outside of this exact discussion and its background (meaning other discussions that have been part of LD4P). If anything, I've heard/seen lexicalization _contrasted_ to recognition as a kind of opposite or dual, with reconciliation (in the stricter sense of id=>id) discussed as a something that happens between those two other processes.

But this might easily be either ambiguous wording that you are about to nail, or my obtuseness and poor reading comprehension!

> Unfortunately, I've seen lexicalization or vocab look-ups being confused with "reconciliation" as of late, so wanted to separate those out here. 

I think we are all on exactly the same page here. Personally, I have no problem at all saying forthrightly-- "Lexicalization is not reconciliation or resolution/recognition, but it is an important nearby process and we are confident that anyone interested in the latter two will end up being interested in the first one, so we're not ashamed or fearful of talking about all of them!"

**Comment by cmharlow** [comment]
I moved it around on the page so it came after some examples of why the group exists (interest in 'reconciliation') but could also then play off of the possibly ambiguous use of 'reconciliation'.

**Comment by aisaac** [comment]
@cmh2166 the new edition is perfect! It does answer all our respective worries, I believe.

**Comment by ajs6f** [comment]
👍 @cmh2166++

**Comment by cmharlow** [comment]
See PR #36 for closing this issue. Anyone here should feel free to merge (or not).
