### ISSUE TITLE
integrate linked data lookup / autocomplete into legacy descriptive system

### ISSUE THREAD

**Issue by tingletech** [LD4P/ld4-community-recon#33]
## Primary Actor

Library catalog repository programmer 

## Scope

If it easy to integrate lookup into legacy systems, it will have an impact of cataloging staff.

## Story

As a repository programmer, I want to integrate a linked data lookup autocomplete into my repository.  Ideally, I don't have to do custom work for each source of linked data.

Needs to support creation of a new term if the term the catalog does not look for does not exist?

**Comment by remerjohnson** [comment]
Honorable mention that although it's rails/samvera specific, the [questioning_authority gem](https://github.com/samvera/questioning_authority) aims to accomplish many of these requirements, and is often used for auto-complete/typeahead functions
