### ISSUE TITLE
the term I need is not found; need to mint a new URI

### ISSUE THREAD

**Issue by tingletech** [LD4P/ld4-community-recon#35]
## Primary Actor

processing descriptive professional (repository or catalog) 

## Scope

Single institution or cooperative?

## Story

As a cataloger assigning controlled headings with linked data, there will be times when the term I'm looking up is not in any authority file already, but I still need to assign some heading.  Need a way to create a new heading on-the-fly with a newly minted URI for the term

**Comment by ajs6f** [comment]
👍 This one is huge.

**Comment by vcharles89** [comment]
I would make the story broader and not only restrict it to subjects headings. This use case is applicable when #47 fails.
