### ISSUE TITLE
Indicate that a match is incorrect

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#44]
## Primary Actor
Cataloger, metadata analyst

## Scope
Applies to systems where local authority records are supported and so annotations of the authority record can be made and retained.

## Story
When attempting to match to an authority, sometimes the user will know that a suggested match is incorrect.  Being able to mark the suggested match as reviewed and incorrect  (e.g. owl:differentFrom) could be useful for either 1) future db wide entity matching or 2) more items being ingested/described which are consistent with the original item, reducing the need to spend as much time researching the two entities again to determine if the match is correct.  This later use case may be especially relevant for institutions who are working with archival or other collections which contain many items relevant to the same entities.

##Related Use Cases
entity match assertions
#39, #60, #72

**Comment by jlhardes** [comment]
This is relevant in association with several of the other use cases. This might be over-arching functionality that needs to be available. Maybe a different sort of category or additional label?

**Comment by ajs6f** [comment]
We _could_ use the Github `project` functionality, but that might be overkill.

**Comment by remerjohnson** [comment]
This would also need some scoping in terms of how this information is harnessed. i.e., would this information just be used by human reviewers, or does a system harness this info? If so, that should be spelled out with expectations / further use cases.

**Comment by ghost** [comment]
Related to #39
