### ISSUE TITLE
Resolve Resource by Label

### ISSUE THREAD

**Issue by kirkhess** [LD4P/ld4-community-recon#46]
## Primary Actor (Required if possible)

Metadata Analyst/Cataloger, or automated system

## Scope (Optional)

System w/ externally resolvable URIs

## Story (Required)

The actor has a string 'label', such as a title for a bibliographic work or a name for an authority, and they want to resolve this label to a resource URI.

This is a type of known-item search which should return a singleton result. Because of the source of labels, consider adding a fuzzy search that is aware of ISBD punctuation rules.

e.g. {base uri}/label/{label}

**Comment by remerjohnson** [comment]
I'm having a hard time envisioning fuzzy matching resulting in a singleton result; seems to be contradictory... is there perhaps more background behind what this use case is attempting differently than reconciliation based on a label, as we have in multiple use cases?
