### ISSUE TITLE
Suggest resource by label

### ISSUE THREAD

**Issue by kirkhess** [LD4P/ld4-community-recon#47]
## Primary Actor (Required if possible)

Metadata Analyst/Cataloger

## Scope (Optional)

System w/ externally resolvable URIs

## Story (Required)

The actor has a string such as portion of the title for a bibliographic work or an undisambiguated name for an authority, and they want to resolve this label to a specific resource URI.  

The expected result is a list of possible matches, or a null result, with enough information for the actor to select a single result.

e.g. {base uri}/suggest?q={label}

**Comment by vcharles89** [comment]
If this method doesn't work then use case #35 would apply.

**Comment by ghost** [comment]
Related to #21, #55, #71
