### ISSUE TITLE
Reconciliation of places  to link objects to places 

### ISSUE THREAD

**Issue by vcharles89** [LD4P/ld4-community-recon#50]
## Primary Actor (Required if possible)

Cataloguer or other metadata experts

## Story (Required)

As a user I want to link places names present in my bibliographical records to places names from a controlled vocabulary such as GeoNames. Before doing so I will need to consolidate places names using a selection of criteria such as name match, type of geographic feature, population, and the origin of the metadata record.

**Useful reference**  (Freire et al. 2011) N. Freire, J. Borbinha, P. Calado, B. Martins. A Metadata Geoparsing System for Place Name Recognition and Resolution in Metadata Records. ACM/IEEE Joint Conference on Digital Libraries, 2011. http://dx.doi.org/10.1145/1998076.1998140

##Related use cases

[https://github.com/LD4P/ld4-community-recon/issues/40] this use case defines the goals for matching like the one from this use case.

**Comment by remerjohnson** [comment]
Mentions #40
