### ISSUE TITLE
Reconciliation of works 

### ISSUE THREAD

**Issue by vcharles89** [LD4P/ld4-community-recon#51]
## Primary Actor (Required if possible)

Cataloguers or metadata experts 

## Story (Required)

As a user I want to link bibliographic records for work  to each other. To do so I will first need to reconcile works based on the work title. 

**Useful reference** (Freire and Juffinger 2011) N. Freire, A. Juffinger. Using National Bibliographies for Rights Clearance. ACM/IEEE Joint Conference on Digital Libraries, 2011. http://dx.doi.org/10.1145/1998076.1998109

##Related use case 
[https://github.com/LD4P/ld4-community-recon/issues/40] this use case defines the goals for matching like the one from this use case.

**Comment by remerjohnson** [comment]
Mentions #40
