### ISSUE TITLE
Permissions problems after github move

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#56]
@cmh2166 Several users (Arwen, Julie, Brian...) are unable to edit the wiki.  Probably related to the github move.

(also for issues: unable to add labels or assign issues)

**Comment by jlhardes** [comment]
To add to https://github.com/LD4P/ld4-community-recon/wiki/External-Communication-Channels:

- Metadata Support Group Slack channel - https://metadatasupportgroup.slack.com
- LD4L Slack channel - ld4.slack.com (this is actually part of Other Communication Methods so maybe not necessary here but good for reaching more than just this working group)

**Comment by tingletech** [comment]
present:
  Brian Tingle, Arwen Hutt, Chrissy Rissmeyer, Arcadia Falcone, Greg Reser, Juilet Hardesty, Ryan Johnson, theodore

text of call for use cases:
  https://github.com/LD4/ld4-community-recon/issues/43
  ^^ will have final text for the call

will make the call for use cases here:
https://github.com/LD4/ld4-community-recon/wiki/External-Communication-Channels

 - [another group/slack mentioned, CR tried to add to wiki during call]
 - DLF Metadata group

individual volenteers to post to these different places?
  ...

technical issues:
  can't edit wiki

keep adding use cases

Issues in Vocabulary Management - National Information Standards ...

http://www.niso.org/apps/group_public/download.php/18054/TR-06-201x_Issues_in_Vocabulary_Management.pdf

entity recognition in the reconciliation work flow -- in scope for use cases? yes

text mining and topic analysis

next meeting in two week

**Comment by cmharlow** [comment]
This should be fixed. @tingletech @arwenhutt @jlhardes please check and confirm.

**Comment by arwenhutt** [comment]
@cmh2166 faster than a speeding bullet! Thanks :)
