### ISSUE TITLE
Finding entities within text

### ISSUE THREAD

**Issue by jlhardes** [LD4P/ld4-community-recon#57]
## Primary Actor (Required if possible)

Cataloger, Metadata Specialist/Analyst

## Scope (Optional)

Institution or consortium, whatever a single repository/cataloging system might cover

## Story (Required)

I need to find distinct entities within text to grab dates or names or places, whether or not they can be reconciled to a Linked Data URI. This might be more text-mining than reconciliation but it was discussed as potentially an initial step in the workflow of reconciliation so possibly it is within the scope of this work.

**Comment by remerjohnson** [comment]
Just to add more info, this is also known as named entity recognition, text analysis, and other various terms. There is a [NER OpenRefine extension](https://github.com/RubenVerborgh/Refine-NER-Extension) (that hopefully still works with newer versions!) that combines the NER step with reconciliation to URIs. 

We may want to evaluate if NER is in scope or not: it is a rather large subject, especially in the digital humanities, and there exists many resources for how to accomplish NER via algorithms executed through bash scripts, R, python etc. [One example resource for R](https://github.com/rochelleterman/text-analysis-dhbsi)
