### ISSUE TITLE
Diverse input

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#58]
Primary Actor
Metadata Specialist

Scope
data integration tool

Story
I have data sets to reconcile in multiple RDF serializations. I do not not want to have to use another tool to re-serialize. In addition I need to access data using a SPARQL endpoint; in fact, I want to input my source data set as well as some target data sets as SPARQL endpoints. We anticipate also the need to input ontologies and possibly other "knowledge" data (dictionaries?), but at present our input is restricted to the matching of source and target datasets in different formats (JSON-LD, RDF-XML, NTriples, Turtle, with the possibility of accessing using SPARQL endpoints).

**Comment by jlhardes** [comment]
Related to #52 - Merging data about same resources (with different data)
