### ISSUE TITLE
External data evaluator

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#65]
Primary Actor
Metadata Specialist

Scope
data integration tool preprocessing

Story
I want to assess the target data set, see if I can figure out how best to match it with our local data. I would like to be able to "push a button" to be able to see the structure of the external data set. What properties are used? From what namespaces? What sorts of values? What else can my smart preprocessor tell me about this external data that might be helpful? Maybe it can crawl around and look for an ontology or rdfs? Maybe it can count how many entities are described using rdf:type and then quantify the types found in that external data.   

Related Use Cases
37, 54

**Comment by jlhardes** [comment]
Agree this is related to #54 and #37
