### ISSUE TITLE
Diverse matching configuration methods

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#67]
Primary Actor
Metadata Specialist

Scope
data integration tool.

Story
Our team wants to be able to configure a source-target matching process but we all have different preferences. Actor 1 prefers a GUI. Actor 2 wants to configure the configuration file directly with a validation file to test the accuracy of the configuration. Actor 3 just wants to use a web form. Other actors are possible...  We want everyone to configure rapidly and as they prefer. Can a tool offer multiple configuration methods? (An example of what we're thinking of as configuration: tell the matching tool, somehow, to find entities of a certain rdf:type; match their labels as tokens; match their dates; establish a threshold; if they exceed that threshold, produce an owl:sameAs relation and download to the desktop. etc.)

**Comment by jlhardes** [comment]
Possibly connected as implementation method for #54
