### ISSUE TITLE
Use ontologies

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#68]
Primary Actor
Metadata Specialist

Scope
data integration tool

Story
I have ontologies for lots of datasets. They're useful, and I want to make use of them. Could I input ontology data and allow my data integration tool to learn additional links/relations? Could I verify matches to external entities by verifying all assertions meet expectations established by the associated ontologies? I would like to use ontologies for data cleaning, data processing and postprocessing. It would be useful if we could do that from the main workflow interface.

**Comment by remerjohnson** [comment]
Seems very close or expanding on #71
