### ISSUE TITLE
Data integration tool with "intelligence"

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#71]
Primary Actor
Entity Recognition Specialist

Scope
data integration tool

Story
I want propose a few exemplary links and have my data integration tool figure out all the appropriate matches between my data set and the target data set. It would be useful if the tool can learn multiple relations. It would be useful if there was transparency (perhaps through a report? A log?) on the matching process.  

Related Use Cases
55, 21

**Comment by remerjohnson** [comment]
Related to #55
