### ISSUE TITLE
Change literal to URI and add assertions

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#72]
Primary Actor
Metadata Specialist

Scope
data integration tool preprocessing

Story
Our data set has a lot of literals as the objects of triples. As an apparent single task we would like to be able to select such literals based on specified criteria and mint local IRIs for those literals, thereby creating new entities. After that we would like to make assertions about a new entity; we would start by using the old literal value as the value of an rdfs:label property (if appropriate). We would then like to make more assertions; most often we find ourselves wanting to state the rdf:type of the new entity, but we would like to have the power to make any appropriate assertion. 

##Related Use Cases
entity match assertions
#39, #44, #60

**Comment by remerjohnson** [comment]
The aspect of minting local URIs makes this similar to #35
