### ISSUE TITLE
Consolidating titles across consortia partners

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#78]
## Primary Actor (Required if possible)

system developer

## Scope (Optional)

library users, my institution, my regional consortium

## Story (Required)

The idea is to be able to consolidate titles from individual institutions that are accessible through a consortia. Titles are exposed through each institution, titles are matched and consolidated into the consortia discovery system.

**Comment by vcharles89** [comment]
It feels to me that in terms of requirements this one could be similar to #85 and #83
