### ISSUE TITLE
Matching e-resource content across multiple vendor knowledge bases

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#80]
## Primary Actor (Required if possible)

e-resource employee

## Scope (Optional)

e-resource employees, e-resource workflow

## Story (Required)

The ability to match e-resource content across multiple vendor knowledge bases. Employee does work in one knowledge base, and then sends the holdings to another knowledge base.

Note that matching on ISSN is problematic.

**Comment by vcharles89** [comment]
#84, #82, #81 and #80 provide good general motivations for reconciliation

**Comment by cmharlow** [comment]
What is the differentiation between knowledge base and other metadata persistence layers (like ILS databases) here?

**Comment by eightBitter** [comment]
I'll try my best to clarify (still a serials noob). We use two knowledge bases for managing serials content: Serials Solutions and a homegrown system called E-Matrix. Serials Solutions is where we manage access to e-resource content, including turning on/off access to journals/databases and managing link resolvers. We also receive 360 MARC records through Serials Solutions that we ingest into our ILS.

E-Matrix serves as an additional knowledge base where we have finer-grained serials management, such as the ability to manage both print and electronic journals/databases.

I'm attaching a serials system diagram that might explain it better than me!

Hope this helps.

![NCSU Libraries Serials System Diagram](https://user-images.githubusercontent.com/7595364/30339896-96d18244-97be-11e7-91f9-57356aac1592.png)
