### ISSUE TITLE
Matching library collections against open access content

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#81]
## Primary Actor (Required if possible)

Systems librarian, librarian who runs analytics

## Scope (Optional)

library patrons, collection managers, my institution

## Story (Required)

The ability to match library collections against open access content in order to assess how much of the library's collection is open access, what paid content is also in open access collections.

**Comment by vcharles89** [comment]
#84, #82, #81 and #80 provide good general motivations for reconciliation

**Comment by cmharlow** [comment]
Assigning this to matching algorithms but it's really about matching to a new source.

**Comment by cmharlow** [comment]
See https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
