### ISSUE TITLE
Reconciling financial data across systems

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#82]
## Primary Actor (Required if possible)

librarians who participate in acquisitions activities

## Scope (Optional)

acquisitions department, financial reconciliation workflow

## Story (Required)

At our institution there's a university-level system for all university financial data, and we manage library financial data in our ILS. We'd like the ability to take financial data from the university system and reconcile it against financial data in the ILS.

**Comment by vcharles89** [comment]
#84, #82, #81 and #80 provide good general motivations for reconciliation

**Comment by cmharlow** [comment]
Hi @eightBitter - is it possible to get an example of what this would look like? We want to clarify the use of 'reconcile' here for our own assessment needs. thanks!

**Comment by eightBitter** [comment]
@cmh2166 sorry for the delay. Here's an explanation from one of my colleagues:

>We have financial data in our ILS and in our campus's procurement system (peoplesoft).  The financial data in ILS is tied to what we ordered or is on order and the financial data in the other system is tied to what's been paid.  Sometimes these numbers are off because of timing (i.e. we ordered something -- that's reflected in the ILS -- but the payment hasn't been entered or gone through yet in peoplesoft); sometimes it's off because of human accounting errors.  Because of that, we created a system of matching records from each system in order to see what's missing from either.

**Comment by cmharlow** [comment]
This seems a bit out of scope for our current project: i.e. we want to explore reconciling / resolving bibliographic data entities even from non-traditional data sources; this feels more like financial or numerical data reconciling. This could perhaps be rewritten to cover the later, but that isn't what we're picking up right now.
