### ISSUE TITLE
Reconciling e-resource packages that have varying names in different data sources

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#83]
## Primary Actor (Required if possible)

System developers

## Scope (Optional)

information supply chain, e-resource employees

## Story (Required)

The ability to reconcile e-resource packages that have varying names in different data sources. Example: take publisher title lists and reconcile e-resource packages across the lists.

**Comment by vcharles89** [comment]
It feels to me that in terms of requirements this use case is similar to #85

**Comment by cmharlow** [comment]
See https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
