### ISSUE TITLE
Reconciling digital special collections that are split among multiple institutions

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#84]
## Primary Actor (Required if possible)

Archivist

## Scope (Optional)

Archivists, the way we collaborate across institutions

## Story (Required)

The ability to reconcile common digital special collections that are split among multiple institutions. Example: Institution A owns pages 1-4 of a digitized text, and Institution B owns pages 5-8. How might Institution A discover that Institution B holds missing items from a work that they own?

**Comment by vcharles89** [comment]
#84, #82, #81 and #80 provide good general motivations for reconciliation

**Comment by cmharlow** [comment]
See https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
