### ISSUE TITLE
Reconciling journal titles against a title family

### ISSUE THREAD

**Issue by eightBitter** [LD4P/ld4-community-recon#85]
## Primary Actor (Required if possible)

e-resource employee

## Scope (Optional)

e-resource employees, information supply chain

## Story (Required)

The ability to reconcile a journal title against its title family. For example, grouping earlier and later titles.

(To be honest, I'm not too familiar with title families, but I can ask one of our e-resource librarians for clarification if needed.)

**Comment by cmharlow** [comment]
This is helpful - thank you! I think I know what is meant by title family, but we can circle around to confirm after the group reviews.

**Comment by cmharlow** [comment]
https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
