### ISSUE TITLE
reconciliation vocabulary

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#86]
Primary Actor: reconciliation/metadata specialist

Story:
As I reconcile my dataset, I want to create metadata about the reconciliation process performed on my dataset as a resource. I would like to describe processes performed on the dataset. For example, I would like to record if the dataset had been "de-duped," that is, if the dataset was checked for duplicate entities with different URIs and duplicates eliminated; I would like to record target vocabularies; I would like to record the predicates chosen to express relationships (owl:sameAs, dcterms:isReferencedBy, skos:closeMatch, etc.). I would like to add this as metadata using a reconciliation vocabulary -- so we want a reconciliation process ontology somehow built into our toolset and shared across institutions. We expect this metadata would be useful to us when matching, to others when targeting our dataset, and to our collaborators/team members in reconciling the dataset.

Related use Cases:
55, 21

**Comment by remerjohnson** [comment]
Related to #55 and #21

**Comment by cmharlow** [comment]
See https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
