### ISSUE TITLE
dereferencing preview

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#87]
Primary Actor:
Metadata/Reconciliation Specialist

Story:
When I mint a new IRI, I would like the option to check if it dereferences successfully and, if so, access a preview of what it dereferences to. I would like to be able to edit the http request so that I can check returns that are not only HTML. 
(Thank you to Yulia Kolesnikova for preparing this use case.)

**Comment by cmharlow** [comment]
See: https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
