### ISSUE TITLE
Enhanced Collaborative Reconciliation

### ISSUE THREAD

**Issue by gerontakos** [LD4P/ld4-community-recon#88]
Primary Actor: Reconciliation Team

Story:
We have several members of the team adding assertions to the same dataset.  We would like to have “enhanced collaborative reconciliation,” with features like online co-authoring and versioning control; for example, real-time editing (so we can see each other's edits as they occur), and version control that allows us to revert to previous versions, create branches that can be worked on independently and merged later, etc. It would be useful to have this all embedded in a single workspace rather than functions of multiple applications.
(Thank you to Yulia Kolesnikova for preparing this use case.)

**Comment by cmharlow** [comment]
+1 - I'm going to label this a system need because it sounds to me like a case we share at my place of work and something that is not about the matching but the system ability to sync updates across actors.

**Comment by cmharlow** [comment]
See https://docs.google.com/spreadsheets/d/1I3jnD3KBWKB1BkWSUZP9XWe9SAH1p_JyFbj4JkA2vrA/edit#gid=577486718
