### ISSUE TITLE
Cross-system identifier matching

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#90]
## Need
Ability to utilize identifiers from one data source for matching to another data source (example: source data has VIAF identifiers, want to be able to use these to identify wikidata records with matching VIAF identifiers).  Using commonly held identifier formats should allow high confidence automated matching which should reduce the necessity (or level) of human review. 

Uses: 
* Pulling specific information not available (consistently) in all vocabularies (birth and death dates, wikipedia links, etc.)
* QA / maintenance of Authority records (cross database comparison to identify gaps or anomalies)
* Facilitate contribution of data to authorities?

## Ideas
* Identify and prioritize data sources and systems which contain cross system identifiers
    * organization identifiers
    * researcher identifiers
* Matching algorithms between systems
    * Include identifying variant formats of identifiers

* ...

## Related submitted use-cases
#79, #74, #64, #48, #45

**Comment by zimeon** [comment]
Archiving this repository (has been inactive since 2017)
