### ISSUE TITLE
Pre-processing scripts for reconciliation

### ISSUE THREAD

**Issue by arwenhutt** [LD4P/ld4-community-recon#91]
## Need
Identify and develop reusable pre-processing scripts for improving data consistency before reconciliation 

Uses:
* improve external reconciliation matching
* improve internal database consistency

## Ideas
* Identify common data clean up tasks that are generally helpful (i.e. changing double spaces to single spaces, removing leading or trailing spaces, etc.)
* Identify any specialized data clean up for improved reconciliation to specific vocabularies (just to make an example up, maybe expanding "Calif." to "California" would improve reconciliation to geonames)
* Identify flexible, usable options for writing/sharing the scripts

## Related submitted use cases
#69, #52 (maybe)

**Comment by zimeon** [comment]
Archiving this repository (has been inactive since 2017)
